Update patch set 9
Patch Set 9:

> > id=4648
 > 
 > That Bug is about "" String value.
 > 
 > There are also failures of this type:
 > java.lang.ClassCastException: Cannot cast java.util.Collections$EmptyList
 > to [B
 > 
 > Which might be addressed by the "bits" part of the fix to Bug 4648
 > (or not).

Bug 4648 moved to mdsal

Patch-set: 9