Update patch set 7
Patch Set 7:

> integration-patch-test-beryllium/71/ : FAILURE (skipped)

There was failure in SingleFeatureTest during pcep build which did not happen in bgpcep verify job:
java.lang.IllegalStateException: Error - getInstance() failed for ModuleIdentifier{factoryName='pcep-topology-provider', instanceName='pcep-topology-provider-instance'} in transaction TransactionIdentifier{name='ConfigTransaction-0-1'}
Caused by: java.net.BindException: Address already in use

Which may be an environment issue of ODL sometimes surviving from a previous build, as describet in https://git.opendaylight.org/gerrit/#/c/29714/2/jjb/integration/include-raw-integration-deploy-controller-verify.sh@33

Let us try again
test-integration

Patch-set: 7