Fix removal of linkstate routes
Fixes the following exception seen when processing MP_UNREACH:

java.lang.ClassCastException: org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.linkstate.rev131125.update.path.attributes.mp.unreach.nlri.withdrawn.routes.destination.type.DestinationLinkstateCaseBuilder$DestinationLinkstateCaseImpl cannot be cast to org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.bgp.linkstate.rev131125.LinkstateDestination
        at org.opendaylight.protocol.bgp.linkstate.LinkstateAdjRIBsIn.removeRoutes(LinkstateAdjRIBsIn.java:214) ~[na:na]
        at org.opendaylight.protocol.bgp.rib.impl.RIBImpl.updateTables(RIBImpl.java:132) ~[na:na]
        at org.opendaylight.protocol.bgp.rib.impl.BGPPeer.onMessage(BGPPeer.java:46) ~[na:na]
        at org.opendaylight.protocol.bgp.rib.impl.BGPPeer.onMessage(BGPPeer.java:32) ~[na:na]
        at org.opendaylight.protocol.bgp.rib.impl.BGPSessionImpl.handleMessage(BGPSessionImpl.java:199) ~[na:na]
        at org.opendaylight.protocol.bgp.rib.impl.BGPSessionImpl.handleMessage(BGPSessionImpl.java:50) ~[na:na]
        at org.opendaylight.protocol.framework.AbstractProtocolSession.channelRead0(AbstractProtocolSession.java:45) ~[na:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[bundlefile:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [bundlefile:na]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [bundlefile:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[na:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [bundlefile:na]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [bundlefile:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[na:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [bundlefile:na]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [bundlefile:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[bundlefile:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) ~[bundlefile:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) ~[bundlefile:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[bundlefile:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[bundlefile:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[bundlefile:na]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]

Change-Id: I95d9b586ddeacbd7bc39500525e8877def604a4c
Signed-off-by: Robert Varga <rovarga@cisco.com>