Update patch set 7
Patch Set 7:

> integration-patch-test-beryllium/72/ : FAILURE (skipped)

BGP tests with -all- [0] had only one additional failure in testcase Check_Listening_Connection_Is_Established_Case_2 (perhaps because some unrelated config files were still being pushed), which is way better than before.

Another job I have looked at is for vpnservice [1]. Bad news is that it got a red dot, because restconf got stuck in 401 status. I retried once [2], and the error in karaf.log is the same:
2015-11-15 17:12:17,308 | ERROR | config-pusher    | ConfigPusherImpl                 | 96 - org.opendaylight.controller.config-persister-impl - 0.4.0.SNAPSHOT | Failed to apply configuration snapshot: 31-bgp.xml(odl-bgpcep-bmp,odl-bgpcep-bmp)
java.lang.IllegalStateException: Unable to push configuration due to missing yang models. Required yang models that are missing: [urn:opendaylight:params:xml:ns:yang:controller:bgp:labeled:unicast?module=odl-bgp-labeled-unicast-cfg&revision=2015-05-25]

I am not sure why this does not happen neither in the BGP job [0] with this Change, nor in Vpnservice job [3] without this change.

[0] https://jenkins.opendaylight.org/releng/job/bgpcep-csit-1node-userfeatures-all-beryllium/751/
[1] https://jenkins.opendaylight.org/releng/job/vpnservice-csit-1node-vpnservice-all-beryllium/656/
[2] https://jenkins.opendaylight.org/releng/job/vpnservice-csit-1node-vpnservice-all-beryllium/657/
[3] https://jenkins.opendaylight.org/releng/job/vpnservice-csit-1node-vpnservice-all-beryllium/659/

Patch-set: 7