Update patch set 1
Patch Set 1:

Hi all,

the 'LSP Identifiers TLV' must be included in the LSP object in PCRpt messages for RSVP-signaled LSPs (draft-ietf-pce-stateful-pce-07). However, in case this path is setup using Segment Routing technique (PST=1) the 'LSP Identifiers TLV' might be not present. In this case LspId is not set in the PathBuilder and the DS operation throws the following exception:

2015-05-08 11:11:03,783 | WARN  | oupCloseable-3-1 | DefaultChannelPipeline           | 104 - io.netty.common - 4.0.26.Final | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: All keys must be specified for class org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.topology.pcep.rev131024.pcep.client.attributes.path.computation.client.reported.lsp.PathKey. Missing key is getLspId. Supplied key is PathKey []

Therefore, the proposed patch set the LspId of the reported LSP to the PLSP-ID received from PCC (in case of SR).

hope this helps
ciao
fra

Patch-set: 1
Reviewer: Gerrit User 2936 <2936@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0