Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review-1
> 
> (4 comments)
> 
> It does not pass at least one Jnuit test. Maybe several ones.
> Can we identify the gap by using temporarily @Ignore in that change ?
> "import org.junit.Ignore;"

Looking at the Junit error, maybe this does not make sense here.

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.opendaylight.odlparent.featuretest.SingleFeatureTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.946 s <<< FAILURE! - in org.opendaylight.odlparent.featuretest.SingleFeatureTest
[ERROR] installFeatureCatchAndLog(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/w/workspace/bgpcep-maven-verify-magnesium-mvn35-openjdk11/features/algo/odl-bgpcep-algo/target/feature/feature.xml, Feature: odl-bgpcep-algo 0.13.0.SNAPSHOT]  Time elapsed: 19.449 s  <<< ERROR!
org.opendaylight.odlparent.bundlestest.lib.SystemStateFailureException: 
diag failed; some bundles failed to start
diag: Failure {Installed=0, Resolved=7, Unknown=0, GracePeriod=0, Waiting=0, Starting=0, Active=242, Stopping=0, Failure=1}
1. NOK org.opendaylight.bgpcep.algo-impl:0.13.0.SNAPSHOT: OSGi state = Active, Karaf bundleState = Failure, due to: Blueprint
2/12/20, 6:58 PM
Exception: 
Unresolved ref/idref to component: rpcServiceRegistry
org.osgi.service.blueprint.container.ComponentDefinitionException: Unresolved ref/idref to component: rpcServiceRegistry

Patch-set: 2